version: '3'
services:
  task:
    build: ./task/
    command: uvicorn app:app --reload --host=0.0.0.0
    volumes:
      - ./task/:/usr/src/app
    ports:
      - "5000:8000"
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=task_user
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - task_db
    networks:
      - task_network
  task_db:
    image: postgres
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - task_network

networks:
  task_network: