version: '3'
services:
  task:
    build: ./services/task/
    command: npm start
    volumes:
      - ./services/task/:/usr/src/app
    ports:
      - "3030:3030"
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_USER=task_user
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - task_db
    networks:
      - task_network
  task_db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_db
      - POSTGRES_PASSWORD=postgres
    networks:
      - task_network

networks:
  task_network:

volumes:
  pgdata:
