apiVersion: v1 
kind: Pod
metadata:
  name: test-pv
spec:
  volumes:
    - name: pvc 
      persistentVolumeClaim:
        claimName: task-pg-pv-claim
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
        - mountPath: "/test/path"
          name: pvc
